---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: ximportedlandingzones.platform.envato.dev
spec:
  group: platform.envato.dev
  names:
    kind: xImportedLandingZone
    plural: ximportedlandingzones
  claimNames:
    kind: ImportedLandingZone
    plural: importedlandingzones
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: imported-landing-zone
  namespace: crossplane-system
spec:
  resources:
  - name: envato-vpc
    patches:
      - fromFieldPath: metadata.annotations
        toFieldPath: metadata.annotations
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: VPC
      spec:
        forProvider:
          region: us-east-1
        providerConfigRef:
          name: aws-provider-config
  compositeTypeRef:
    apiVersion: platform.envato.dev/v1alpha1
    kind: xImportedLandingZone
...